name: Deploy Extension

on:
  push:
    branches:
      - main
    paths:
      - "package.json"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Read version
        id: pkg
        run: echo "VERSION=$(jq -r .version package.json)" >> $GITHUB_ENV

      - name: Create and push git tag
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          # すでに存在していたらスキップ
          if git rev-parse "v${VERSION}" >/dev/null 2>&1; then
            echo "Tag v${VERSION} already exists, skipping."
          else
            git tag "v${VERSION}"
            git push origin "v${VERSION}"
          fi

      - uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: "npm"
      - run: npm ci

      - name: Publish to Open VSX Registry
        id: publishToOpenVSX
        uses: HaaLeo/publish-vscode-extension@v2
        with:
          pat: ${{ secrets.OPEN_VSX_TOKEN }}
      - name: Publish to Visual Studio Marketplace
        uses: HaaLeo/publish-vscode-extension@v2
        with:
          pat: ${{ secrets.VS_MARKETPLACE_TOKEN }}
          registryUrl: https://marketplace.visualstudio.com
          extensionFile: ${{ steps.publishToOpenVSX.outputs.vsixPath }}
